- name: Configura iptables
  hosts: all
  become: yes
  tasks:
  - name: Flush iptables
    command:
      cmd: iptables -P INPUT ACCEPT && iptables -P OUTPUT ACCEPT && iptables -P FORWARD ACCEPT && iptables -F && iptables --flush
  - name: Allow connections on http(s)
    tags: iptables
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_ports:
        - "80"
        - "443"
      jump: ACCEPT